export const counties = [
  'avon',
  'bedfordshire',
  'berkshire',
  'buckinghamshire',
  'cambridgeshire',
  'cheshire',
  'cornwall',
  'cumbria',
  'derbyshire',
  'devon',
  'dorset',
  'durham',
  'essex',
  'gloucestershire',
  'greater London',
  'hampshire',
  'herefordshire',
  'hertfordshire',
  'isle of Wight',
  'kent',
  'lancashire',
  'leicestershire',
  'lincolnshire',
  'merseyside',
  'norfolk',
  'northamptonshire',
  'northumberland',
  'nottinghamshire',
  'oxfordshire',
  'rutland',
  'schools',
  'shropshire',
  'somerset',
  'staffordshire',
  'suffolk',
  'surrey',
  'sussex',
  'tyne and Wear',
  'warwickshire',
  'west Midlands',
  'wiltshire',
  'worcestershire',
  'yorkshire',
];
